# Generated by Django 4.2.9 on 2024-06-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_template', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceTemplate',
            new_name='Template',
        ),
        migrations.DeleteModel(
            name='InternalInvoiceFormat',
        ),
        migrations.DeleteModel(
            name='TemplateMapping',
        ),
    ]
